### ISSUE TITLE
Ping latency reports as 0ms in status queries

### ISSUE THREAD

**Issue by kivster** [sparky8512/starlink-grpc-tools#100]
The Home assistant Starlink integration reports ping in milliseconds. Since a recent Starlink update on 22nd November,  the ping is now incorrectly reading 0ms continuously in Home Assistant.

Starlink version 2024.11.13.mr45845.2
HA Core 2024.11.2

![IMG_2963](https://github.com/user-attachments/assets/73e2f389-3652-41ac-9995-ff5e2acb3fb4)

The ping  measurement inside the Starlink App - Median value is present but latest is not.

![IMG_2964](https://github.com/user-attachments/assets/173fd233-efbc-406f-bd75-0101f2a2860f)

All other Home Assistant Starlink metrics appear to be OK.

![IMG_2966](https://github.com/user-attachments/assets/246d0f8c-d96f-49c4-b4b0-25b557157202)

I’m assuming this is a bug/issue in the recent Starlink update, but raising this for awareness. Feel free to close this issue if this is the case and there’s nothing that can be done.

**Comment by DeanCording** [comment]
Seems to be related to a recent firmware update:

```
id:                    ut01000000-00000000-00094ecd
hardware_version:      rev2_proto3
software_version:      2024.11.18.mr46048.1
state:                 CONNECTED
uptime:                65470
snr:                   
seconds_to_first_nonempty_slot: 0.0
pop_ping_drop_rate:    0.0
downlink_throughput_bps: 11903.4345703125
uplink_throughput_bps: 2441.0849609375
pop_ping_latency_ms:   0.0
Alerts bit field:      0
fraction_obstructed:   0.0
currently_obstructed:  False
seconds_obstructed:    
obstruction_duration:  
obstruction_interval:  
direction_azimuth:     154.7001190185547
direction_elevation:   59.600833892822266
is_snr_above_noise_floor: True
```

**Comment by sparky8512** [comment]
It seems they stopped populating that field in the status response, even though there is nothing in the protocol spec that has changed to mark it deprecated. It's still there in the history data, which is what the Starlink app uses for the page OP posted image of.

I'll have a look at augmenting the status query with the history data.

**Comment by sparky8512** [comment]
After further consideration, I'm uncertain whether or not this was an intended change in the firmware. As OP noted, the "latest" value is not populated in the Starlink app, which may be due to it pulling that value out of status. That page clearly has the history data, so it could just as easily just populate that "latest" number with the most recent history sample.

So anyway, I can pretty easily change the status query to also pull the history data and return the latency number from that, but if this was unintended behavior in the firmware, it may get changed back in later firmware. I think I will go ahead and make the change, anyway, as I can always back it out later.

**Comment by sparky8512** [comment]
That change should fix it, but I have a bunch more testing to do before I tag a new release.

**Comment by sparky8512** [comment]
OK, testing done and this is now published as v1.2.1, including the core module on PyPI (which I think is what the Home Assistant integration uses) and Docker image.

**Comment by kivster** [comment]
Thank you!

**Comment by kivster** [comment]
FYI in the most recent Starlink update the latest latency metric is working again

Starlink 2024.12.17.mr47156.1

![image](https://github.com/user-attachments/assets/d0239b78-b75d-47bf-bda5-3087c4b8cc28)

**Comment by sparky8512** [comment]
Yes, I noticed that got fixed on my dish, too. I'm going to give it a few more weeks to make sure the firmware has rolled out to everyone, then back out the workaround to remove the need for the extra history query.
