### ISSUE TITLE
Is it possible to track the current connected satellite id?

### ISSUE THREAD

**Issue by ItakEjgo** [sparky8512/starlink-grpc-tools#102]
Hi,

I’m wondering if it’s possible to identify the satellite currently in use. It appears there was a function, dish_get_context, that could provide the satellite ID, but this call seems to be unavailable now.

Could you provide any alternative methods for identifying the connected satellite?

**Comment by sparky8512** [comment]
I'm pretty sure the short answer is no.

The `dish_get_context` request is still there, but it returns an authorization error when run locally. I'm not even sure it has the actual current satellite ID, anyway. There is also a `transceiver_get_telemetry` request that does have what might be current satellite ID, but that also returns an authorization error when run locally. It could be that these can only be run remotely, or they might be locked down in some other way.

I suppose it would be technically possible to track the satellites by resetting the obstruction map, examining where new map data fills in, and correlating that with satellite position data, but doing so would require periodically resetting the map and that would probably impact the dish's ability to avoid obstructions.

**Comment by ItakEjgo** [comment]
> I'm pretty sure the short answer is no.
> 
> The `dish_get_context` request is still there, but it returns an authorization error when run locally. I'm not even sure it has the actual current satellite ID, anyway. There is also a `transceiver_get_telemetry` request that does have what might be current satellite ID, but that also returns an authorization error when run locally. It could be that these can only be run remotely, or they might be locked down in some other way.
> 
> I suppose it would be technically possible to track the satellites by resetting the obstruction map, examining where new map data fills in, and correlating that with satellite position data, but doing so would require periodically resetting the map and that would probably impact the dish's ability to avoid obstructions.

Thanks for your reply!
