### ISSUE TITLE
SNR may have broken with a recent update

### ISSUE THREAD

**Issue by dustin** [sparky8512/starlink-grpc-tools#34]
Just got `3155b85a-29b0-4de0-8c5e-c23c321bf245.uterm.release` and I've not looked into it much, but at least my SNR graph looks broken while the rest of the stuff seems to be working.

<img width="1498" alt="Screen Shot 2021-10-17 at 10 32 35" src="https://user-images.githubusercontent.com/1779/137638419-bde09c5e-56ae-4bc1-b64b-6adc6498c3be.png">

**Comment by sparky8512** [comment]
Yeah, sadly SNR was removed in that firmware update. A bunch of other fields, too.

I was going to drop a note in the README, but I didn't want something that was essentially a temporary notice cluttering that up (further...). Maybe I should have kept the issue tracking this (#32) open so people could see it had already come to my attention.
