### ISSUE TITLE
dump_dish_status.py fails

### ISSUE THREAD

**Issue by Llaves** [sparky8512/starlink-grpc-tools#47]
It tries to import module starlink.api.device, which is not installed by the requirements.txt file.

**Comment by sparky8512** [comment]
As noted in the README, that script assumes you have the [generated gRPC protocol modules](https://github.com/sparky8512/starlink-grpc-tools/wiki/gRPC-Protocol-Modules) in place. Those are not publicly available from a pip repository, as far as I am aware.

**Comment by Llaves** [comment]
I focused too much on the earlier note about not needing to generate the gRPC protocol modules and thought that overrode the later note. My error.

**Comment by sparky8512** [comment]
The wording was a little awkward, so I clarified it in the README.
