### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by itemir** [sparky8512/starlink-grpc-tools#50]
Some gRPC calls require authentication. Do you know how this works? 

Example:

```
$ grpcurl -plaintext -d {\"dish_get_emc\":{}} 192.168.100.1:9200 SpaceX.API.Device.Device/Handle
ERROR:
  Code: PermissionDenied
  Message:
$
```

**Comment by sparky8512** [comment]
Assuming there are no further questions regarding this (not that I really have any more information to answer them), I'm going to close it out.
