### ISSUE TITLE
Did Starlink disable the gRPC/web interface?

### ISSUE THREAD

**Issue by ferventgeek** [sparky8512/starlink-grpc-tools#76]
Thanks again for this exporter! It was amazing, but a few months ago stopped working for me. My LAN is a 10., with a static route to 192.168.100.1 in the router, out to the Gen 2 Dishy via the ethernet adapter. Again, it was working fine for months. 

Now, neither the gRPC or nor legacy metrics web server seem to be available, and Starlink support has no answers. Has anyone else seen gRPC go from working to vanished?

**Comment by sparky8512** [comment]
It still works for me. I have the round dish, but I expect I would have heard complaints by now if the tools stopped working for the newer dishes.

Does the web app at http://192.168.100.1 respond at all? If not, it's probably a routing issue somewhere, and I would start troubleshooting with a traceroute.

If it does load, but just won't show dish status, then I'm not sure, maybe a firewall rule in your router?

**Comment by ferventgeek** [comment]
Thank you. Maybe this is a Gen2 thing and they killed the interface? I'm wondering if the other possibility is that it won't open sockets not from its 192.168.100 subnet. Works fine using the Starlink router/wifi. Thanks again- great project!
