### ISSUE TITLE
Zabbix Template for Starlink Dishy

### ISSUE THREAD

**Issue by smejdil** [sparky8512/starlink-grpc-tools#78]
Hi
I am using your project to monitor Starlink Dish using Prometeus exporter. I'm uploading templates for Zabbix 6.0
[https://github.com/smejdil/zabbix-starlink](https://github.com/smejdil/zabbix-starlink)

**Comment by sparky8512** [comment]
Cool! Would you mind if I added links to those files on this project's Wiki (probably by expanding the scope of the [Dashboards](https://github.com/sparky8512/starlink-grpc-tools/wiki/Dashboards) page)?  ... or you could do so yourself, if you like, the page should be editable by anyone.

**Comment by smejdil** [comment]
Templates can be published anywhere. It may be updated in time. So it is advisable to use my link.

**Comment by sparky8512** [comment]
Thanks. I see you have updated the Wiki page so I will close this issue out.
