### ISSUE TITLE
wifi_util.proto missing

### ISSUE THREAD

**Issue by mcba** [sparky8512/starlink-grpc-tools#79]
When generating the .proto files, I think you are missing wifi_util.proto. This can be generated as follows:

python3 -m grpc_tools.protoc --descriptor_set_in=../dish.protoset --python_out=. --grpc_python_out=. spacex/api/device/wifi_util.proto

**Comment by sparky8512** [comment]
Thanks for pointing that out. I have updated the Wiki page for this.  Some day I'll write a script that does this automatically, it's not that difficult...
