### ISSUE TITLE
Unknown Alert code 384

### ISSUE THREAD

**Issue by smejdil** [sparky8512/starlink-grpc-tools#80]
Hi
I monitoring my Starlink v2. And i detect alert with code 384. Do you know what the code means? You might want to add the code to starlink_grpc.py?

**Comment by sparky8512** [comment]
You mean the `alerts` field in the status group? That one is a bitfield, so if you have multiple alerts active, there will be multiple bits set. 384 in binary is 110000000, which is 256 + 128, which is `alert_is_heating` and `alert_install_pending`.

If you pull the alert_detail group, it should have the alerts listed individually.

**Comment by smejdil** [comment]
Hi
Thank you for the explanation. I added Items "Alert detail status" to my Zabbix templates
