### ISSUE TITLE
Please make a bare linux type instal. I don't use Dockerfile

### ISSUE THREAD

**Issue by Mudary** [sparky8512/starlink-grpc-tools#99]
Please have an un-dockerize version. Plus pipx doesn't like a non-debian install unless you use a virtual environment.
Thanks
corrected spelling

**Comment by Mudary** [comment]
pip install sv-ttk and any other pip commands. I was able to use the vm commands and install but it doesn't install on the computer.

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by Mudary** [comment]
https://grpc.io/docs/languages/python/quickstart/

If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.

If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.

See /usr/share/doc/python3.12/README.venv for more information.

**Comment by sparky8512** [comment]
I guess Linux distros have started marking the system libs as externally managed and directing people to use virtual envs instead.

It is a good idea to use a venv for this project (or any other Python-based project). I didn't include it in the install instructions because I thought anyone who wanted to use it would already know how, and the instructions vary a little across systems. But if it's going to be required for some distros, I will add a note to the README.
